/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumUsuarioRol } from "./EnumUsuarioRol";
import { EnumUsuarioRoles } from "./EnumUsuarioRoles";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";

@InputType()
class UsuarioWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nombre?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  password?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumUsuarioRol,
  })
  @IsEnum(EnumUsuarioRol)
  @IsOptional()
  @Field(() => EnumUsuarioRol, {
    nullable: true,
  })
  rol?: "Option1";

  @ApiProperty({
    required: false,
    enum: EnumUsuarioRoles,
  })
  @IsEnum(EnumUsuarioRoles)
  @IsOptional()
  @Field(() => EnumUsuarioRoles, {
    nullable: true,
  })
  roles?: "Option1";

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  lastLoginAt?: DateTimeNullableFilter;
}

export { UsuarioWhereInput as UsuarioWhereInput };
