/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RecetaService } from "../receta.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RecetaCreateInput } from "./RecetaCreateInput";
import { Receta } from "./Receta";
import { RecetaFindManyArgs } from "./RecetaFindManyArgs";
import { RecetaWhereUniqueInput } from "./RecetaWhereUniqueInput";
import { RecetaUpdateInput } from "./RecetaUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RecetaControllerBase {
  constructor(
    protected readonly service: RecetaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Receta })
  @nestAccessControl.UseRoles({
    resource: "Receta",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReceta(@common.Body() data: RecetaCreateInput): Promise<Receta> {
    return await this.service.createReceta({
      data: {
        ...data,

        producto: data.producto
          ? {
              connect: data.producto,
            }
          : undefined,

        materiaPrima: data.materiaPrima
          ? {
              connect: data.materiaPrima,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        cantidadNecesaria: true,

        producto: {
          select: {
            id: true,
          },
        },

        materiaPrima: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Receta] })
  @ApiNestedQuery(RecetaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Receta",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async recetas(@common.Req() request: Request): Promise<Receta[]> {
    const args = plainToClass(RecetaFindManyArgs, request.query);
    return this.service.recetas({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        cantidadNecesaria: true,

        producto: {
          select: {
            id: true,
          },
        },

        materiaPrima: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Receta })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Receta",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async receta(
    @common.Param() params: RecetaWhereUniqueInput
  ): Promise<Receta | null> {
    const result = await this.service.receta({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        cantidadNecesaria: true,

        producto: {
          select: {
            id: true,
          },
        },

        materiaPrima: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Receta })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Receta",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReceta(
    @common.Param() params: RecetaWhereUniqueInput,
    @common.Body() data: RecetaUpdateInput
  ): Promise<Receta | null> {
    try {
      return await this.service.updateReceta({
        where: params,
        data: {
          ...data,

          producto: data.producto
            ? {
                connect: data.producto,
              }
            : undefined,

          materiaPrima: data.materiaPrima
            ? {
                connect: data.materiaPrima,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          cantidadNecesaria: true,

          producto: {
            select: {
              id: true,
            },
          },

          materiaPrima: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Receta })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Receta",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReceta(
    @common.Param() params: RecetaWhereUniqueInput
  ): Promise<Receta | null> {
    try {
      return await this.service.deleteReceta({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          cantidadNecesaria: true,

          producto: {
            select: {
              id: true,
            },
          },

          materiaPrima: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
