/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { CostoListRelationFilter } from "../../costo/base/CostoListRelationFilter";
import { VentaListRelationFilter } from "../../venta/base/VentaListRelationFilter";
import { RecetaListRelationFilter } from "../../receta/base/RecetaListRelationFilter";

@InputType()
class ProductoWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nombre?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  descripcion?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  precioVenta?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => CostoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CostoListRelationFilter)
  @IsOptional()
  @Field(() => CostoListRelationFilter, {
    nullable: true,
  })
  costos?: CostoListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => VentaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VentaListRelationFilter)
  @IsOptional()
  @Field(() => VentaListRelationFilter, {
    nullable: true,
  })
  ventas?: VentaListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RecetaListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RecetaListRelationFilter)
  @IsOptional()
  @Field(() => RecetaListRelationFilter, {
    nullable: true,
  })
  recetas?: RecetaListRelationFilter;
}

export { ProductoWhereInput as ProductoWhereInput };
