/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { CostoCreateNestedManyWithoutProductosInput } from "./CostoCreateNestedManyWithoutProductosInput";
import { Type } from "class-transformer";
import { VentaCreateNestedManyWithoutProductosInput } from "./VentaCreateNestedManyWithoutProductosInput";
import { RecetaCreateNestedManyWithoutProductosInput } from "./RecetaCreateNestedManyWithoutProductosInput";

@InputType()
class ProductoCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descripcion?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  precioVenta?: number | null;

  @ApiProperty({
    required: false,
    type: () => CostoCreateNestedManyWithoutProductosInput,
  })
  @ValidateNested()
  @Type(() => CostoCreateNestedManyWithoutProductosInput)
  @IsOptional()
  @Field(() => CostoCreateNestedManyWithoutProductosInput, {
    nullable: true,
  })
  costos?: CostoCreateNestedManyWithoutProductosInput;

  @ApiProperty({
    required: false,
    type: () => VentaCreateNestedManyWithoutProductosInput,
  })
  @ValidateNested()
  @Type(() => VentaCreateNestedManyWithoutProductosInput)
  @IsOptional()
  @Field(() => VentaCreateNestedManyWithoutProductosInput, {
    nullable: true,
  })
  ventas?: VentaCreateNestedManyWithoutProductosInput;

  @ApiProperty({
    required: false,
    type: () => RecetaCreateNestedManyWithoutProductosInput,
  })
  @ValidateNested()
  @Type(() => RecetaCreateNestedManyWithoutProductosInput)
  @IsOptional()
  @Field(() => RecetaCreateNestedManyWithoutProductosInput, {
    nullable: true,
  })
  recetas?: RecetaCreateNestedManyWithoutProductosInput;
}

export { ProductoCreateInput as ProductoCreateInput };
