/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { CostoUpdateManyWithoutProductosInput } from "./CostoUpdateManyWithoutProductosInput";
import { Type } from "class-transformer";
import { VentaUpdateManyWithoutProductosInput } from "./VentaUpdateManyWithoutProductosInput";
import { RecetaUpdateManyWithoutProductosInput } from "./RecetaUpdateManyWithoutProductosInput";

@InputType()
class ProductoUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  descripcion?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  precioVenta?: number | null;

  @ApiProperty({
    required: false,
    type: () => CostoUpdateManyWithoutProductosInput,
  })
  @ValidateNested()
  @Type(() => CostoUpdateManyWithoutProductosInput)
  @IsOptional()
  @Field(() => CostoUpdateManyWithoutProductosInput, {
    nullable: true,
  })
  costos?: CostoUpdateManyWithoutProductosInput;

  @ApiProperty({
    required: false,
    type: () => VentaUpdateManyWithoutProductosInput,
  })
  @ValidateNested()
  @Type(() => VentaUpdateManyWithoutProductosInput)
  @IsOptional()
  @Field(() => VentaUpdateManyWithoutProductosInput, {
    nullable: true,
  })
  ventas?: VentaUpdateManyWithoutProductosInput;

  @ApiProperty({
    required: false,
    type: () => RecetaUpdateManyWithoutProductosInput,
  })
  @ValidateNested()
  @Type(() => RecetaUpdateManyWithoutProductosInput)
  @IsOptional()
  @Field(() => RecetaUpdateManyWithoutProductosInput, {
    nullable: true,
  })
  recetas?: RecetaUpdateManyWithoutProductosInput;
}

export { ProductoUpdateInput as ProductoUpdateInput };
